### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by he3als** [f0e/blur#13]
Hello, will there ever be Linux support for this project?

**Comment by Aetopia** [comment]
Adding Linux support would make total sense.

**Comment by applesfruit** [comment]
Yeah, that would be a great addition to blur, connecting to a different range of users.
I have tried with Wine (on pop_os), it doesn't work, but I believe that it would be very hard trying to convert blur into Linux supported app.

**Comment by he3als** [comment]
It works on Wine, it is just annoying to setup and it is not worth it over just using an ffmpeg command.

**Comment by applesfruit** [comment]
Hmmm, is there something that is similar to SendTo (Windows) on Linux?

**Comment by Kminh1209hary** [comment]
> Hmmm, is there something that is similar to SendTo (Windows) on Linux?

You will need terminal emulator support or you need to make your own UI. You should do a "paste the file path here: " first because it is the easiest.

**Comment by ferencKx** [comment]
This need to be a thing, or atleast have a simple guide in readme for running it with Wine if possible

**Comment by Avyukt-Ballari** [comment]
fr their needs to be linux support

**Comment by he3als** [comment]
https://github.com/animafps/teres

**Comment by f0e** [comment]
It's supported now, you'll need to install the dependencies yourself though. I'll try get an appimage made sometime maybe

**Comment by tfkhdyt** [comment]
I tried the Linux version, but I'm getting this error:

Script evaluation failed:
File reading exception:
[Errno 2] No such file or directory: '/home/tfkhdyt/.local/bin/lib/blur.py'

I'm using v2.03, and I've already installed ffmpeg and VapourSynth.

**Comment by tfkhdyt** [comment]
When I disable gpu encoding (amd), I get this error instead:

```
[in#0 @ 0x57364fa9ba80] Error opening input: Invalid data found when processing input
Error opening input file -.
Error opening input files: Invalid data found when processing input
```

**Comment by f0e** [comment]
Gonna reopen this as the main Linux issue till I get some form of installer working

**Comment by f0e** [comment]
> When I disable gpu encoding (amd), I get this error instead:
> 
> ```
> [in#0 @ 0x57364fa9ba80] Error opening input: Invalid data found when processing input
> Error opening input file -.
> Error opening input files: Invalid data found when processing input
> ```

This is likely due to some vapoursynth plugins missing. I'm going to try set it all up on Linux today and I'll write my steps as I go

**Comment by nnra6864** [comment]
I just got the latest one on arch, tried opening the file via GUI and got this:
`RIFE model 'rife-v4.26_ensembleFalse' could not be found`
CLI didn't throw any errors:
```
./blur-cli-Linux-Release-x64 -i "/home/nnra/Downloads/Test.mkv" -o "/home/nnra/Downloads/Blur-Linux-Release-x64/"
created
Rendering 'Test'

Finished rendering
removing temp path /tmp/blur-6
```
However, there is no file at that location :/

**Comment by nnra6864** [comment]
Also, the latest version just crashes when I try to open the config in GUI, [v2.03](https://github.com/f0e/blur/releases/tag/v2.03) doesn't.

**Comment by f0e** [comment]
You can try downloading [rife-v4.26_ensembleFalse](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/tree/master/models/rife-v4.26_ensembleFalse) into `models/` alongside the binary and it should work with [this build](https://github.com/f0e/blur/actions/runs/14635479596). Haven't tested though, but I think it should be fine.

I'm not sure about the GUI crashing, will have to get back to you on that. I haven't tested any versions past the ones in [here](https://github.com/f0e/blur/pull/148) so yeah they'll probably be unstable.

re: AppImage for anyone still curious - annoyingly creating it was much harder than I expected, it works on some distros but not others. Shared library woes. Partially gave up on it but I'll try again soon, busy with other stuff atm.

**Comment by nnra6864** [comment]
Hmm, it's looking for blur.py too:
```
Script evaluation failed:
File reading exception:
[Errno 2] No such file or directory: '/home/nnra/Downloads/Blur-Linux-Release-x64/lib/blur.py'
```
As for dependencies being a pain when it comes to AppImage, why not list deps in readme, and then people could take on maintaining packages for different distros.
If not that, even tho I am not a huge fan of flatpak, could it be a better option than AppImage here?

**Comment by khuza08** [comment]
> Hmm, it's looking for blur.py too:
> 
> ```
> Script evaluation failed:
> File reading exception:
> [Errno 2] No such file or directory: '/home/nnra/Downloads/Blur-Linux-Release-x64/lib/blur.py'
> ```
> 
> As for dependencies being a pain when it comes to AppImage, why not list deps in readme, and then people could take on maintaining packages for different distros. If not that, even tho I am not a huge fan of flatpak, could it be a better option than AppImage here?

I encountered the exact same error on Arch Linux. It might be helpful if all required dependencies were clearly listed in the README—this would make it much easier for other users to get things running smoothly.

**Comment by f0e** [comment]
Added a list of dependencies and updated the Linux release artifacts to include the proper `/lib` and RIFE model files. Works fine for me on a fresh VM going through the process of installing everything and running. Let me know if stuff's still confusing and I'll add more detail :)

**Comment by f0e** [comment]
Build out with Linux stuff packaged https://github.com/f0e/blur/releases/tag/v2.15

**Comment by nnra6864** [comment]
Question, what are we supposed to do with dll-s and so-s we manually downloaded?

**Comment by f0e** [comment]
Vapoursynth plugin `so`s by default are loaded from /usr/local/lib/vapoursynth, so they should go there. (At least with my version - built from git main)

<img width="293" alt="Image" src="https://github.com/user-attachments/assets/e3f32de9-5fe0-4032-aab6-ec2e374a6d7c" />

**Comment by nnra6864** [comment]
Hey, thanks for pointing it out, they were all available in AUR.
Here's the install command, use your pm ofc:
`paru -S vapoursynth ffmpeg vapoursynth-plugin-svpflow vapoursynth-plugin-bestsource vapoursynth-plugin-mvtools vapoursynth-plugin-vsakarin-av1an-git`
Keep in mind I used [akarin-av1an](https://aur.archlinux.org/packages/vapoursynth-plugin-vsakarin-av1an-git) instead of regular [akarin](https://aur.archlinux.org/packages/vapoursynth-plugin-vsakarin-git) because it was failing to build, lmk if you get it working.

**Comment by nnra6864** [comment]
Config page is still crashing for me tho.

**Comment by f0e** [comment]
> Hey, thanks for pointing it out, they were all available in AUR. Here's the install command, use your pm ofc: `paru -S vapoursynth ffmpeg vapoursynth-plugin-svpflow vapoursynth-plugin-bestsource vapoursynth-plugin-mvtools vapoursynth-plugin-vsakarin-av1an-git` Keep in mind I used [akarin-av1an](https://aur.archlinux.org/packages/vapoursynth-plugin-vsakarin-av1an-git) instead of regular [akarin](https://aur.archlinux.org/packages/vapoursynth-plugin-vsakarin-git) because it was failing to build, lmk if you get it working.

Nice, I'll add that info to the readme. That makes things much nicer.
On Akarin - yeah, building it is very annoying, it requires LLVM 12. The fork supposedly supports newer versions, but I had issues with anything above 16. I think that version on AUR is correct though.

> Config page is still crashing for me tho.

Is rendering working? I'll try on an Arch VM when I can now that I know installation is easy and try figure out what's crashing.

**Comment by nnra6864** [comment]
Sadly not, I tried the CLI, reported the issue in #103.
GUI appears starts rendering but eventually fails:
```
Information: VideoSource track #0 index progress 0%
Information: VideoSource track #0 index progress 6%
Information: VideoSource track #0 index progress 11%
Information: VideoSource track #0 index progress 16%
Information: VideoSource track #0 index progress 24%
Information: VideoSource track #0 index progress 34%
Information: VideoSource track #0 index progress 43%
Information: VideoSource track #0 index progress 55%
Information: VideoSource track #0 index progress 70%
Information: VideoSource track #0 index progress 81%
Information: VideoSource track #0 index progress 93%
Script evaluation failed:
Python exception: No attribute with the name rife exists. Did you mistype a plugin namespace or forget to install a plugin?

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluate
  File "/home/nnra/Downloads/blur-Linux-Release-x64/lib/blur.py", line 154, in <module>
    video = blur.interpolate.interpolate_rife(
        video,
    ...<2 lines>...
        gpu_index=rife_gpu_index,
    )
  File "/home/nnra/Downloads/blur-Linux-Release-x64/lib/blur/interpolate.py", line 191, in interpolate_rife
    video = core.rife.RIFE(
            ^^^^^^^^^
  File "src/cython/vapoursynth.pyx", line 2895, in vapoursynth._CoreProxy.__getattr__
  File "src/cython/vapoursynth.pyx", line 2701, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name rife exists. Did you mistype a plugin namespace or forget to install a plugin?
```

It appears to be caused by rife, didn't you say you included that in the build?

**Comment by f0e** [comment]
OOPS. yep, missed that, sorry. Don't know why I didn't get an error when testing. Installing this should fix it https://aur.archlinux.org/packages/vapoursynth-plugin-rife-ncnn-vulkan

**Comment by nnra6864** [comment]
Yeah, appears to be working now.
Thanks a lot for all the support you provided!

![Image](https://github.com/user-attachments/assets/6b080ec5-3bef-4f9a-a5e5-0ae07b77f13b)

**Comment by f0e** [comment]
Another update, Linux releases now include the required vapoursynth plugins, and when a `vapoursynth-plugins` folder exists alongside the blur binaries the plugins are read from there.

You can also modify `vapoursynth lib path` in `blur.cfg` to fix "Failed to initialize VapourSynth environment" or similar errors by specifying your VapourSynth library path if it isn't standard - see https://www.vapoursynth.com/doc/installation.html for more info, the option sets `LD_LIBRARY_PATH` and `PYTHONPATH`

**Comment by nnra6864** [comment]
> Another update, Linux releases now include the required vapoursynth plugins, and when a vapoursynth-plugins folder exists alongside the blur binaries the plugins are read from there.

Very welcome addition.
However, I did get an error due to having all the dependencies installed on my system too.
I am not sure whether this is expected, but I fixed it by renaming the vs dir to `vapoursynth-plugins_bak`.
Here's the error I got when I input a clip:
```
Script evaluation failed:
Python exception: Plugin ../vapoursynth-plugins/bestsource.so already loaded (com.vapoursynth.bestsource) from /usr/lib/vapoursynth/bestsource.so

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluate
  File "/home/nnra/Packages/blur-Linux-Release-x64/lib/blur.py", line 30, in <module>
    core.std.LoadPlugin(path=str(plugin))
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "src/cython/vapoursynth.pyx", line 3123, in vapoursynth.Function.__call__
vapoursynth.Error: Plugin ../vapoursynth-plugins/bestsource.so already loaded (com.vapoursynth.bestsource) from /usr/lib/vapoursynth/bestsource.so
```

**Comment by f0e** [comment]
Good catch, didn't know they threw errors on duplicate plugin loads. I'll fix that

**Comment by f0e** [comment]
fixed in https://github.com/f0e/blur/commit/dd29c5992754216f1eb73967f8bb8b2a5c7a13f1 / https://github.com/f0e/blur/releases/tag/v2.31

**Comment by f0e** [comment]
Going to close this since I feel like Linux is supported enough at this point. I've made a feature request (https://github.com/f0e/blur/issues/235) for creating an AppImage and adding to package managers
