### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by M70000** [f0e/blur#18]
Well, i did everything on the installation right but when i start the rendering i get this error:

`Script evaluation failed:`
`Python exception: 'utf-8' codec can't decode byte 0xe9 in position 160: invalid continuation byte`

`Traceback (most recent call last):`
  `File "src\cython\vapoursynth.pyx", line 2239, in vapoursynth.vpy_evaluateScript`
  `File "encodings\utf_8_sig.py", line 23, in decode`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 160: invalid continuation byte`

`pipe:: Invalid data found when processing input`

**Comment by couleurm** [comment]
try resetting your blur config / try in another folder with a fresh config

**Comment by M70000** [comment]
it didn't worked :(

**Comment by chchee3300** [comment]
you should put your vid file in a english folder, I got the same issue and fixed by just make a non-chinese folder lol

**Comment by couleurm** [comment]
Non Alphanumeric (e.g cyrilic) don't do too well in paths with blur

**Comment by Snowy2908** [comment]
> 비디오 파일을 영어 폴더에 인쇄해야 합니다. 대칭적인 문제가 등록되어 있지 않고 폴더를 생성했습니다.

nice i fixed it

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
