### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by rawo-neti** [f0e/blur#21]
Script evaluation failed:
Python exception: No attribute with the name fmtc exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "C:\Users\godra\Desktop\\blur_temp\9M5LhF.vpy", line 7, in <module>
    video = core.fmtc.matrix(clip=video, mat="601", col_fam=vs.YUV, bits=16)
  File "src\cython\vapoursynth.pyx", line 1891, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 1754, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name fmtc exists. Did you mistype a plugin namespace?

pipe:: Invalid data found when processing input

**Comment by couleurm** [comment]
Reinstall using the `blur-installer.exe`, just downloading and running `blur.exe` won't work

**Comment by TalhaDaddy** [comment]
still getting same error

**Comment by Al3rtFun** [comment]
Do converting file to mp4, its help for me, maybe it can help u

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
