### ISSUE TITLE
fd:: Invalid data found when processing input

### ISSUE THREAD

**Issue by HardBucks** [f0e/blur#43]
I dont know how to fix this, i have zero experience of coding.
I tried:
-Reseting config
-Reinstall Installer-blur.exe
-Restart PC
-run installer.bat
-Manual install

Heres the error code looks like :
`
Deprecated option --y4m specified, use -c y4m instead
Script evaluation failed:
Python exception: No module named 'vsutil'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "C:\Users\HardBucks\Desktop\video\\blur_temp\AEGMj1.vpy", line 3, in <module>
    import havsfunc as haf
  File "C:\Users\HardBucks\AppData\Roaming\Python\Python311\site-packages\havsfunc.py", line 71, in <module>
    from vsutil import Dither, depth, fallback, get_depth, get_y, join, plane, scale_value
ModuleNotFoundError: No module named 'vsutil'

fd:: Invalid data found when processing input
`
if anyone know solution to fix this, i would appreciate it

**Comment by ZirczWare** [comment]
same problem here, no fixes yet

**Comment by whit3cat3** [comment]
try to remove all the non-english symbols, that helped me

**Comment by Spok-en** [comment]
Go to cmd and type `pip install vsutil`

**Comment by redd555** [comment]
did anyone find away

**Comment by AffectAspect** [comment]
try removing your config file, cuz it worked for me

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
