### ISSUE TITLE
i'm too stupid to understand this help

### ISSUE THREAD

**Issue by ghrave** [f0e/blur#5]
Deprecated option --y4m specified, use -c y4m instead
Script evaluation failed:
Python exception: No module named 'havsfunc'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2788, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2789, in vapoursynth._vpy_evaluate
  File "C:\Users\zzzz\Videos\shadowplay\Desktop\\blur_temp\evyAha.vpy", line 3, in <module>
    import havsfunc as haf
ModuleNotFoundError: No module named 'havsfunc'

pipe:: Invalid data found when processing input

**Comment by f0e** [comment]
You have to install the requirements
