### ISSUE TITLE
Script evaluation failed: Python exception: Source: No video track found

### ISSUE THREAD

**Issue by NotDevNoob** [f0e/blur#67]
![image](https://github.com/f0e/blur/assets/112945980/4cc057ca-3c1a-4ee6-a03f-db6d094d6cae)
Script evaluation failed:
Python exception: Source: No video track found

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "C:\Users\andre\OneDrive\Desktop\\blur_temp\rkh4mp.vpy", line 6, in <module>
    video = core.ffms2.Source(source="C:/Users/andre/OneDrive/Desktop/vhjdfg d.mp4", cache=False)
  File "src\cython\vapoursynth.pyx", line 2067, in vapoursynth.Function.__call__
vapoursynth.Error: Source: No video track found

pipe:: Invalid data found when processing input

                                               finished rendering vhjdfg d

 ----------------------------------------------------------------------------------------------------------------------

                                        finished render queue, waiting for input.

**Comment by NotDevNoob** [comment]
fixed it just found out its the video thats broken

**Comment by matskobinks** [comment]
got the same problem but theres a video

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
