### ISSUE TITLE
My video isn't rendering

### ISSUE THREAD

**Issue by GameKing1205** [f0e/blur#88]
One day my pc ssd files corrupted (If this is useful)
then it resets my pc
after that i cant use my blur app
it keeps show this error

Script evaluation failed:
Python exception: Source: No video track found

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "C:\Users\user\Desktop\blur\\blur_temp\m2tNlo.vpy", line 7, in <module>
    video = core.ffms2.Source(source="C:/Users/user/Desktop/blur/video.mp4", cache=False)
  File "src\cython\vapoursynth.pyx", line 2067, in vapoursynth.Function.__call__
vapoursynth.Error: Source: No video track found

pipe:: Invalid data found when processing input

i tried downloading vapoursynth and python and more and it didn't work
can someone help me pls
                                                finished rendering video

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
