### ISSUE TITLE
script evaluation failed/invalid data found 

### ISSUE THREAD

**Issue by paulitoxd** [f0e/blur#89]
hello, when i put my clip (recorded from obs) in blur, I have this message : 

Script evaluation failed:
Python exception: 'utf-8' codec can't decode byte 0xa0 in position 187: invalid start byte

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2239, in vapoursynth.vpy_evaluateScript
  File "encodings\utf_8_sig.py", line 23, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 187: invalid start byte

pipe:: Invalid data found when processing input

                           finished rendering caca

If someone can help me, would be great :p

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
