### ISSUE TITLE
pipe:: Invalid data found when processing input

### ISSUE THREAD

**Issue by sui390503** [f0e/blur#95]
Script evaluation failed:
Python exception: Source: Video track is unseekable

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "C:\Users\reo-ron\Desktop\\blur_temp\FUZEN1.vpy", line 6, in <module>
    video = core.ffms2.Source(source="C:/Users/reo-ron/Desktop/Documents.mp4", cache=False)
  File "src\cython\vapoursynth.pyx", line 2067, in vapoursynth.Function.__call__
vapoursynth.Error: Source: Video track is unseekable

pipe:: Invalid data found when processing input

i cant do it

**Comment by MotWnb** [comment]
me too

**Comment by MotWnb** [comment]
Script evaluation failed:
Python exception: 'utf-8' codec can't decode byte 0xd6 in position 175: invalid continuation byte

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2239, in vapoursynth.vpy_evaluateScript
  File "encodings\utf_8_sig.py", line 23, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 175: invalid continuation byte

pipe:: Invalid data found when processing input

**Comment by Left-My-Game** [comment]
did you fix it?

**Comment by MotWnb** [comment]
try to use an older version
---- Replied Message ----
From ***@***.***> Date 01/24/2025 11:23 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [f0e/blur] pipe:: Invalid data found when processing input (Issue #95) 
did you fix it?

**Comment by f0e** [comment]
Bulk-closing old issues due to 2.0 release which should solve most common problems. If your issue remains feel free to create a new ticket or reply in here with updated information.
